name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-cmake_3_29_2:
    runs-on: ubuntu-22.04

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: cmake3_29_2.Dockerfile
        push: true
        tags: kbryon/cpp-build-envs:cmake3.29.2
        cache-from: type=registry,ref=kbryon/cpp-build-envs:cmake3.29.2
        cache-to: type=inline

  build-clang16:

    runs-on: ubuntu-22.04
    needs: build-cmake_3_29_2

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: clang16.Dockerfile
        push: true
        tags: kbryon/cpp-build-envs:clang16
        cache-from: type=registry,ref=kbryon/cpp-build-envs:clang16
        cache-to: type=inline
  
  build-clang17:

    runs-on: ubuntu-22.04
    needs: build-cmake_3_29_2

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: clang17.Dockerfile
        push: true
        tags: kbryon/cpp-build-envs:clang17
        cache-from: type=registry,ref=kbryon/cpp-build-envs:clang17
        cache-to: type=inline

  build-clang18:

    runs-on: ubuntu-22.04
    needs: build-cmake_3_29_2

    env:
      Version: 18

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: clang18.Dockerfile
        push: true
        tags: kbryon/cpp-build-envs:clang18
        cache-from: type=registry,ref=kbryon/cpp-build-envs:clang18
        cache-to: type=inline

