name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-clang16:

    runs-on: ubuntu-22.04

    env:
      Version: 16

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: clang$Version.Dockerfile
        push: true
        tags: kbryon/cpp-build-envs:clang$Version
        cache-from: type=registry,ref=kbryon/cpp-build-envs:clang$Version
        cache-to: type=inline
  
  build-clang17:

    runs-on: ubuntu-22.04

    env:
      Version: 17

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: clang$Version.Dockerfile
        push: true
        tags: kbryon/cpp-build-envs:clang$Version
        cache-from: type=registry,ref=kbryon/cpp-build-envs:clang$Version
        cache-to: type=inline

  build-clang18:

    runs-on: ubuntu-22.04

    env:
      Version: 18

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: clang$Version.Dockerfile
        push: true
        tags: kbryon/cpp-build-envs:clang$Version
        cache-from: type=registry,ref=kbryon/cpp-build-envs:clang$Version
        cache-to: type=inline

