name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file clang17.Dockerfile --tag kbryon/cpp-build-envs:clang17
    - name: Push the Docker image
      run: docker push kbryon/cpp-build-envs:clang17
